version: "3"

services:
  db_mongo:
    image: mongo
    restart: always
    volumes:
      - ./db/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db_mongo

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db_mongo
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://root:root@localhost:27017/db_mongo



# version: "3"

# services:
#   db_mongo:
#     image: mongo
#     restart: always
#     volumes:
#       - ./data:/data/db
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: root
#       MONGO_INITDB_DATABASE: db_mongo
#   api:
#     image: datascientest/fastapi:1.0.0
#     restart: always
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db_mongo #fast api à besoin que db soit lancé d'abord
#     app:
#       build:
#         context: .
#         dockerfile: Dockerfile
#       restart: always
#       ports:
#         - "80:80"
#       depends_on:
#         - api
       