version: "3.10"

services:

  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    ports: 
      - "5432:5432"
    networks:
      - api_net
    restart: unless-stopped

  mongo:
    container_name: mongo 
    image: mongo
    volumes:
      - ../data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db_mongo
    ports: 
      - "27017:27017"
    networks: 
      - api_net
    restart: unless-stopped
  
  api:
    container_name: api
    image: api
    depends_on:
      - postgres
      #- mongo
    networks:
      - api_net
    ports:
      - "8000:8000"


networks:
  api_net:  
    external:
      name: api_net  
