version: "3.9"

services:

  postgres:
    container_name: postgres_container
    image: postgres:latest
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    networks:
      - dock_net
    restart: unless-stopped
  
  mongo:
    container_name: mongo_container
    image: mongo:5.0
    volumes:
      - ../data/mongo:/data/db
    ports: 
      - "27017:27017"
    networks: 
      - dock_net
    restart: unless-stopped

  api:
    container_name: api_container
    image: api_image:latest
    depends_on:
      - postgres
      - mongo
    networks:
      - dock_net
    ports:
      - "8000:8000"

  streamlit:
    container_name: streamlit_container
    image: streamlit_image:latest
    depends_on:
      - api
    networks:
      - dock_net
    ports:
      - "8501:8501"

networks:
  dock_net:
    external:
      name: dock_net 

