FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    unzip \
    && rm -rf /var/lib/apt/lists/*

COPY ExtractData.sh /app
COPY etl.py /app
COPY requirements.txt /app
COPY transformData.py /app
COPY streamlit.py /app

RUN pip3 install -r requirements.txt
RUN sh ExtractData.sh
RUN python3 transformData.py
RUN python3 etl.py

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]